### ISSUE TITLE
您好，可以出个通用版的吗

### ISSUE THREAD

**Issue by felix2chow** [mohuishou/notion-blog-actions#2]
我看代码里用到了ali oos 能否出个实现功能的最简版并加一些注释，帮助一下小白，感谢您

**Comment by mohuishou** [comment]
这个后续加一下哈

**Comment by felix2chow** [comment]
感谢，期待

**Comment by mohuishou** [comment]
可以了哈，见最新的 readme 即可

**Comment by felix2chow** [comment]
1、配置示例notion_secret报错
Warning: Unexpected input(s) 'notion_secret', valid inputs are ['token', 'database_id', 'status_name', 'status_published', 'status_unpublish', 'migrate_image', 'output', 'access_key_id', 'access_key_secret', 'bucket', 'area', 'prefix']
2、notion_secret修改成token报错
(node:1623) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
@notionhq/client warn: request fail { code: 'unauthorized', message: 'API token is invalid.' }
/home/runner/work/_actions/mohuishou/notion-blog-actions/main/dist/index.js:4172
        return new APIResponseError({
               ^

APIResponseError: API token is invalid.
    at Object.buildRequestError (/home/runner/work/_actions/mohuishou/notion-blog-actions/main/dist/index.js:4172:[16](https://github.com/felix2chow/testnotionhugo/actions/runs/3354328993/jobs/5557800923#step:3:17))
    at Client.request (/home/runner/work/_actions/mohuishou/notion-blog-actions/main/dist/index.js:3768:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getPages (/home/runner/work/_actions/mohuishou/notion-blog-actions/main/dist/index.js:216590:14)
    at async Object.sync (/home/runner/work/_actions/mohuishou/notion-blog-actions/main/dist/index.js:216568:15)
    at async /home/runner/work/_actions/mohuishou/notion-blog-actions/main/dist/index.js:230664:3 {
  code: 'unauthorized',
  status: 401,
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      date: [ 'Sun, 30 Oct 2022 06:03:33 GMT' ],
      'content-type': [ 'application/json; charset=utf-8' ],
      'content-length': [ '87' ],
      connection: [ 'close' ],
      'set-cookie': [
        'notion_browser_id=45[18](https://github.com/felix2chow/testnotionhugo/actions/runs/3354328993/jobs/5557800923#step:3:19)22a8-88d5-4068-908e-e4f4f879b6ab; Domain=www.notion.so; Path=/; Expires=Mon, 30 Oct [20](https://github.com/felix2chow/testnotionhugo/actions/runs/3354328993/jobs/5557800923#step:3:21)23 06:03:33 GMT; Secure',
        'notion_check_cookie_consent=false; Domain=www.notion.so; Path=/; Expires=Mon, 31 Oct 2022 06:03:33 GMT; Secure'
      ],
      'content-security-policy': [
        "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://gist.github.com https://apis.google.com https://www.google.com https://www.gstatic.com https://cdn.amplitude.com https://api.amplitude.com https://hkfxbbdzib.notion.so https://widget.intercom.io https://js.intercomcdn.com https://static.zdassets.com https://api.smooch.io\t https://logs-01.loggly.com https://http-inputs-notion.splunkcloud.com https://cdn.segment.com https://analytics.pgncs.notion.so https://o324374.ingest.sentry.io https://checkout.stripe.com https://js.stripe.com https://embed.typeform.com https://admin.typeform.com https://public.profitwell.com js.sentry-cdn.com https://js.chilipiper.com https://platform.twitter.com https://cdn.syndication.twimg.com https://accounts.google.com https://www.googletagmanager.com https://www.googleadservices.com https://googleads.g.doubleclick.net https://api-v2.mutinyhq.io https://client-registry.mutinycdn.com https://client.mutinycdn.com https://user-data.mutinycdn.com https://cdn01.boxcdn.net;connect-src 'self' https://msgstore.www.notion.so wss://msgstore.www.notion.so ws://localhost:* ws://127.0.0.1:* https://notion-emojis.s3-us-west-2.amazonaws.com https://s3-us-west-2.amazonaws.com https://s3.us-west-2.amazonaws.com https://notion-production-snapshots-2.s3.us-west-2.amazonaws.com https://cdn.amplitude.com https://api.amplitude.com https://hkfxbbdzib.notion.so https://www.notion.so https://api.embed.ly https://js.intercomcdn.com https://api-iam.intercom.io https://uploads.intercomcdn.com wss://nexus-websocket-a.intercom.io https://ekr.zdassets.com https://ekr.zendesk.com\t https://makenotion.zendesk.com\t https://api.smooch.io\t wss://api.smooch.io\t https://logs-01.loggly.com https://http-inputs-notion.splunkcloud.com https://cdn.segment.com https://api.segment.io https://analytics.pgncs.notion.so https://api.pgncs.notion.so https://o324374.ingest.sentry.io https://checkout.stripe.com https://js.stripe.com https://cdn.contentful.com https://preview.contentful.com https://images.ctfassets.net https://www2.profitwell.com https://tracking.chilipiper.com https://api.chilipiper.com https://api.unsplash.com https://boards-api.greenhouse.io https://accounts.google.com https://oauth2.googleapis.com https://www.googletagmanager.com https://analytics.google.com https://www.googleadservices.com https://googleads.g.doubleclick.net https://region1.google-analytics.com https://region1.analytics.google.com https://www.google-analytics.com https://api-v2.mutinyhq.io https://client-registry.mutinycdn.com https://client.mutinycdn.com https://user-data.mutinycdn.com https://api.statuspage.io https://pgncd.notion.so https://api.statsig.com https://statsigapi.net https://exp.notion.so https://file.notion.so https://api.box.com;font-src 'self' data: https://cdnjs.cloudflare.com https://js.intercomcdn.com https://cdn01.boxcdn.net;img-src 'self' data: blob: https: https://platform.twitter.com https://syndication.twitter.com https://pbs.twimg.com https://ton.twimg.com https://region1.google-analytics.com https://region1.analytics.google.com;style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://github.githubassets.com https://js.chilipiper.com https://platform.twitter.com https://ton.twimg.com https://accounts.google.com https://cdn01.boxcdn.net;frame-src https: http: https://accounts.google.com;media-src https: http: https://file.notion.so"
      ],
      'x-dns-prefetch-control': [ 'off' ],
      'x-frame-options': [ 'SAMEORIGIN' ],
      'strict-transport-security': [ 'max-age=5184000; includeSubDomains' ],
      'x-download-options': [ 'noopen' ],
      'x-content-type-options': [ 'nosniff' ],
      'x-permitted-cross-domain-policies': [ 'none' ],
      'referrer-policy': [ 'strict-origin-when-cross-origin' ],
      'x-xss-protection': [ '0' ],
      etag: [ 'W/"57-QCRLT3IovYEW+CkwyJQlFtiXiG8"' ],
      vary: [ 'Accept-Encoding' ],
      'cf-cache-status': [ 'DYNAMIC' ],
      server: [ 'cloudflare' ],
      'cf-ray': [ '76[21](https://github.com/felix2chow/testnotionhugo/actions/runs/3354328993/jobs/5557800923#step:3:22)f2cb6973ea02-DFW' ]
    }
  },
  body: '{"object":"error","status":[40](https://github.com/felix2chow/testnotionhugo/actions/runs/3354328993/jobs/5557800923#step:3:41)1,"code":"unauthorized","message":"API token is invalid."}'
}
